name: Build and Release

# 触发条件：当创建新标签时（通常用于版本发布）自动触发，或手动触发
on:
  push:
    tags:
      - 'v*' # 匹配所有以v开头的标签，如v1.0.0
  # 添加手动触发功能
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (自动生成格式: yyMMdd.hhMM)'
        required: true
        default: 'auto_version'
      prerelease:
        description: '是否为预发布版本'
        required: true
        type: boolean
        default: true

# 添加所需的权限配置
permissions:
  contents: write     # 允许推送到仓库和创建发布
  discussions: write  # 如果需要在讨论中发布，则添加此权限

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置执行权限
        run: chmod +x build.sh

      - name: 运行打包脚本
        run: ./build.sh

      - name: 获取版本号
        id: get_version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            # 如果是手动触发并且版本号设置为自动生成，则使用当前时间格式
            if [[ "${{ github.event.inputs.version }}" == "auto_version" ]]; then
              # 生成格式：yyMMdd.hhmm
              VERSION="v$(date +'%y%m%d.%H%M')"
              echo "使用自动生成的版本号: $VERSION"
            else
              VERSION="${{ github.event.inputs.version }}"
            fi
            PRERELEASE="${{ github.event.inputs.prerelease }}"
          else
            VERSION=${GITHUB_REF#refs/tags/}
            PRERELEASE=false
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "PRERELEASE=$PRERELEASE" >> $GITHUB_OUTPUT

      - name: 创建 Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: ZeroTier Gateway ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: ${{ steps.get_version.outputs.PRERELEASE }}
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          files: |
            zerotier-gateway-bundle.sh
          body: |
            # ZeroTier Gateway ${{ steps.get_version.outputs.VERSION }}
            
            这是使用GitHub Actions自动打包的ZeroTier高级网关脚本。
            
            ## 使用方法
            
            1. 下载 `zerotier-gateway-bundle.sh` 文件
            2. 设置执行权限: `chmod +x zerotier-gateway-bundle.sh`
            3. 运行脚本: `./zerotier-gateway-bundle.sh`
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}